---
- name: Copy .conf file to server
  action: copy src=templates/mynewsite.conf dest=/etc/apache2/sites-available/example.com.conf owner=root group=root mode=0644
- name: Create sym link from sites-enabled
  file: src=/etc/apache2/sites-available/example.com.conf dest=/etc/apache2/sites-enabled/example.com.conf owner=root group=root state=link
- name: enable mpm_event module
  apache2_module: name=mpm_event state=present
- name: a2ensite example.com
  command: a2ensite example.com
  notify: Restart HTTPD
