---
- name: Create DMZ Network
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Create a new DMZ Network
      clc_network:
        location: 'AU1'
        state: present
        name: 'DMZ VLAN'
        description: 'DMZ VLAN'
      register: net
- name: Create TRUST Network
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Create a new Trust Network
      clc_network:
        location: 'AU1'
        state: present
        name: 'TRUST VLAN'
        description: 'TRUST VLAN'
      register: net
- name: Create Groups
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Create Web Server Group
      clc_group:
        name: 'Production Web Servers'
        parent: 'AU1 Hardware'
        location: AU1
        state: present
      register: clc
    - name: Create SQL Server Group
      clc_group:
        name: 'Production SQL Servers'
        parent: 'AU1 Hardware'
        location: AU1
        state: present
      register: clc
    - name: Create Infra Server Group
      clc_group:
        name: 'Production Infra Servers'
        parent: 'AU1 Hardware'
        location: AU1
        state: present
      register: clc
    - name: Create Dev Server Group
      clc_group:
        name: 'Development Servers'
        parent: 'AU1 Hardware'
        location: AU1
        state: present
      register: clc
- name: Build Web Servers
  hosts: localhost
  serial: 3
  gather_facts: false
  connection: local
  tasks:
  - name: Deploy Production Web Servers
    clc_server:
      cpu: 1
      memory: 4
      description: 'Production Web Server'
      location: AU1
      group: 'Production Web Servers'
      managed_os: false
      name: WEB
      network_id: 'DMZ VLAN'
      primary_dns: 208.67.222.222
      secondary_dns: 208.67.220.220
      type: standard
      storage_type: standard
      template: WIN2012R2DTC-64
      count: 3
    register: clc
- name: Build SQL Server
  hosts: localhost
  serial: 1
  gather_facts: false
  connection: local
  tasks:
  - name: Deploy Production SQL Server
    clc_server:
      cpu: 2
      memory: 8
      description: 'SQL Server'
      location: AU1
      group: 'Production SQL Servers'
      managed_os: false
      name: MSSQL
      network_id: 'TRUST VLAN'
      primary_dns: 208.67.222.222
      secondary_dns: 208.67.220.220
      type: standard
      storage_type: standard
      template: WIN2012R2DTC-64
      count: 1
    register: clc
- name: Build File Server
  hosts: localhost
  serial: 1
  gather_facts: false
  connection: local
  tasks:
  - name: Deploy Production Infrastructure Servers
    clc_server:
      cpu: 1
      memory: 4
      description: 'File Server'
      location: AU1
      group: 'Production Infra Servers'
      managed_os: false
      name: FILE
      network_id: 'TRUST VLAN'
      primary_dns: 208.67.222.222
      secondary_dns: 208.67.220.220
      type: standard
      storage_type: standard
      template: WIN2012R2DTC-64
      count: 1
    register: clc
- name: Build Dev Server
  hosts: localhost
  serial: 1
  gather_facts: false
  connection: local
  tasks:
  - name: Deploy Dev Servers
    clc_server:
      cpu: 1
      memory: 4
      description: 'Dev Web Server'
      location: AU1
      group: 'Development Servers'
      managed_os: false
      name: DEVWEB
      network_id: 'TRUST VLAN'
      primary_dns: 208.67.222.222
      secondary_dns: 208.67.220.220
      type: standard
      storage_type: standard
      template: WIN2012R2DTC-64
      count: 1
    register: clc
- name: Create Firewall Policy
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Create Firewall Policy from DMZ to TRUST
      clc_firewall_policy:
        source_account_alias: CCVA
        location: AU1
        state: present
        source: ['DMZ VLAN']
        destination: ['TRUST VLAN']
        ports: ['TCP/1433, ICMP']
        destination_account_alias: CCVA
- name: Add CPU alert policies for Demo
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Create CPU alert policy
      clc_alert_policy:
        alias: CCVA
        name: 'CPU Alert'
        alert_recipients:
            - no-reply@ctl.io
        metric: 'cpu'
        duration: '00:15:00'
        threshold: 90
        state: present
      register: clc
- name: Add Memory alert policies for Demo
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Create Memory alert policy
      clc_alert_policy:
        alias: CCVA
        name: 'Memory Alert'
        alert_recipients:
            - no-reply@ctl.io
        metric: 'memory'
        duration: '00:15:00'
        threshold: 80
        state: present
      register: clc
- name: Add Disk alert policies for Demo
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Create Disk alert policy
      clc_alert_policy:
        alias: CCVA
        name: 'Disk Alert'
        alert_recipients:
            - no-reply@ctl.io
        metric: 'disk'
        duration: '00:5:00'
        threshold: 80
        state: present
      register: clc
- name: Apply CPU Alert Policies
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: add alert policy to servers
      clc_modify_server:
        server_ids:
            - WEB
            - MSSQL
            - FILE
            - DEVWEB
        alert_policy_name: 'CPU Alert'
        state: present
- name: Apply Memory Alert Policies
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: add alert policy to servers
      clc_modify_server:
        server_ids:
            - WEB
            - MSSQL
            - FILE
            - DEVWEB
        alert_policy_name: 'Memory Alert'
        state: present
- name: Apply Disk Alert Policies
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: add alert policy to servers
      clc_modify_server:
        server_ids:
            - WEB
            - MSSQL
            - FILE
            - DEVWEB
        alert_policy_name: 'Disk Alert'
        state: present
